import { ReactNode } from 'react';

import Head from 'next/head';

import { Layout as AntLayout } from 'antd';

const { Content, Footer } = AntLayout;

import Header from '@/components/Header/Header';

type LayoutProps = {
  children: ReactNode;
  title?: string;
};

export default function Layout({
  children,
  title = 'Rick and Morty Characters App',
}: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AntLayout
        className="layout"
        style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}
      >
        <Header />
        <Content style={{ flex: 1 }}>{children}</Content>
        <Footer style={{ textAlign: 'center' }}>
          Avdoshkina Design ©2023
        </Footer>
      </AntLayout>
    </>
  );
}
